# fly.toml file generated for black-sunset-753 on 2023-05-17T12:56:46+03:00

app = "black-sunset-753"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "waw"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
